{"uuid": "f3433c4c-d1e6-4345-90b9-24b13e2373a6", "children": ["84adff11-07ab-4c25-8df1-7d00b1edc81e"], "befores": [{"name": "mock_fn", "status": "broken", "statusDetails": {"message": "ModuleNotFoundError: No module named 'mocker_over_mock'\n", "trace": "  File \"D:\\Workspace\\Practice\\Venvs\\github_project\\lib\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n  File \"D:\\Workspace\\Practice\\Venvs\\github_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n  File \"D:\\Workspace\\Practice\\Venvs\\github_project\\lib\\site-packages\\_pytest\\fixtures.py\", line 908, in call_fixture_func\n    fixture_result = fixturefunc(**kwargs)\n  File \"C:\\Program Files\\Python310\\lib\\unittest\\mock.py\", line 1366, in patched\n    with self.decoration_helper(patched,\n  File \"C:\\Program Files\\Python310\\lib\\contextlib.py\", line 135, in __enter__\n    return next(self.gen)\n  File \"C:\\Program Files\\Python310\\lib\\unittest\\mock.py\", line 1348, in decoration_helper\n    arg = exit_stack.enter_context(patching)\n  File \"C:\\Program Files\\Python310\\lib\\contextlib.py\", line 492, in enter_context\n    result = _cm_type.__enter__(cm)\n  File \"C:\\Program Files\\Python310\\lib\\unittest\\mock.py\", line 1421, in __enter__\n    self.target = self.getter()\n  File \"C:\\Program Files\\Python310\\lib\\unittest\\mock.py\", line 1608, in <lambda>\n    getter = lambda: _importer(target)\n  File \"C:\\Program Files\\Python310\\lib\\unittest\\mock.py\", line 1247, in _importer\n    thing = __import__(import_path)\n"}, "start": 1678268172804, "stop": 1678268172804}], "start": 1678268172804, "stop": 1678268172967}